-- ============================================================
-- Zlinks Package System — PostgreSQL 15+ 初始化脚本
-- ============================================================
-- 使用前请先创建数据库:
--   createdb zlinks_package_system
-- 然后执行:
--   psql -d zlinks_package_system -f init-database-pgsql.sql
-- ============================================================

-- 通用触发器函数: 自动更新 update_time
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.update_time = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ==========================
-- 游戏表
-- ==========================
CREATE TABLE IF NOT EXISTS game (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_name       VARCHAR(100) NOT NULL,
    game_direction  VARCHAR(20) NOT NULL,
    source          VARCHAR(50),
    git_url         VARCHAR(255),
    priority        INT DEFAULT 0,
    tags            VARCHAR(255),
    project_type    VARCHAR(50),
    manager         VARCHAR(50),
    white_branch    VARCHAR(100),
    status          VARCHAR(20) DEFAULT 'active',
    retention_record TEXT,
    android_folder_name VARCHAR(100),
    remark          TEXT,
    create_by       VARCHAR(64) DEFAULT '',
    update_by       VARCHAR(64) DEFAULT '',
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE game IS '游戏表';
CREATE TRIGGER trg_game_update_time BEFORE UPDATE ON game
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- 平台表
-- ==========================
CREATE TABLE IF NOT EXISTS platform (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_name   VARCHAR(100) NOT NULL,
    platform_code   VARCHAR(50),
    sort_order      INT DEFAULT 0,
    status          VARCHAR(20) DEFAULT 'active',
    remark          TEXT,
    create_by       VARCHAR(64) DEFAULT '',
    update_by       VARCHAR(64) DEFAULT '',
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE platform IS '平台表';
CREATE TRIGGER trg_platform_update_time BEFORE UPDATE ON platform
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- 软著表
-- ==========================
CREATE TABLE IF NOT EXISTS copyright (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    copyright_name  VARCHAR(100) NOT NULL,
    copyright_owner VARCHAR(100),
    copyright_number VARCHAR(50),
    remark          TEXT,
    create_by       VARCHAR(64) DEFAULT '',
    update_by       VARCHAR(64) DEFAULT '',
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE copyright IS '软著表';
CREATE TRIGGER trg_copyright_update_time BEFORE UPDATE ON copyright
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- 主体公司表
-- ==========================
CREATE TABLE IF NOT EXISTS company (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name    VARCHAR(100) NOT NULL,
    platform_id     BIGINT,
    account         VARCHAR(100),
    password        VARCHAR(100),
    remark          TEXT,
    create_by       VARCHAR(64) DEFAULT '',
    update_by       VARCHAR(64) DEFAULT '',
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE company IS '主体公司表';
CREATE TRIGGER trg_company_update_time BEFORE UPDATE ON company
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- 平台匹配表
-- ==========================
CREATE TABLE IF NOT EXISTS platform_match (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT REFERENCES company(id),
    original_game   VARCHAR(100),
    current_game_name VARCHAR(100),
    batch           VARCHAR(50),
    package_mode    VARCHAR(20),
    sdk_version     VARCHAR(50),
    apk_version     VARCHAR(20),
    platform_status VARCHAR(20) DEFAULT 'pending',
    remark          TEXT,
    create_by       VARCHAR(64) DEFAULT '',
    update_by       VARCHAR(64) DEFAULT '',
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE platform_match IS '平台匹配表';
CREATE TRIGGER trg_platform_match_update_time BEFORE UPDATE ON platform_match
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- 产品表
-- ==========================
CREATE TABLE IF NOT EXISTS product (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    copyright_id    BIGINT REFERENCES copyright(id),
    game_id         BIGINT REFERENCES game(id),
    company_id      BIGINT REFERENCES company(id),
    platform_id     BIGINT,
    package_name    VARCHAR(100),
    sdk_version     VARCHAR(50),
    apk_version     VARCHAR(50),
    batch           VARCHAR(50),
    package_mode    VARCHAR(20),
    status          VARCHAR(20) DEFAULT 'pending',
    remark          TEXT,
    create_by       VARCHAR(64) DEFAULT '',
    update_by       VARCHAR(64) DEFAULT '',
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE product IS '产品表';
CREATE TRIGGER trg_product_update_time BEFORE UPDATE ON product
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- 荣耀参数表
-- ==========================
CREATE TABLE IF NOT EXISTS honor_param (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      BIGINT NOT NULL REFERENCES product(id),
    package_name    VARCHAR(100),
    app_id          VARCHAR(100),
    app_secret      VARCHAR(100),
    media_id        VARCHAR(100),
    agconnect_path  VARCHAR(255),
    td_app_id       VARCHAR(100),
    ad_param_status VARCHAR(20),
    list_status     VARCHAR(20),
    operator        VARCHAR(50),
    remark          TEXT,
    create_by       VARCHAR(64) DEFAULT '',
    update_by       VARCHAR(64) DEFAULT '',
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE honor_param IS '荣耀参数表';
CREATE TRIGGER trg_honor_param_update_time BEFORE UPDATE ON honor_param
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- VIVO参数表
-- ==========================
CREATE TABLE IF NOT EXISTS vivo_param (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      BIGINT NOT NULL REFERENCES product(id),
    app_id          VARCHAR(100),
    contract_status VARCHAR(20),
    media_id        VARCHAR(100),
    td_app_id       VARCHAR(100),
    ad_param_status VARCHAR(20),
    list_status     VARCHAR(20),
    operator        VARCHAR(50),
    remark          TEXT,
    create_by       VARCHAR(64) DEFAULT '',
    update_by       VARCHAR(64) DEFAULT '',
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE vivo_param IS 'VIVO参数表';
CREATE TRIGGER trg_vivo_param_update_time BEFORE UPDATE ON vivo_param
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- HUAWEI参数表
-- ==========================
CREATE TABLE IF NOT EXISTS huawei_param (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      BIGINT NOT NULL REFERENCES product(id),
    package_name    VARCHAR(100),
    app_id          VARCHAR(100),
    agconnect_path  VARCHAR(255),
    td_app_id       VARCHAR(100),
    ad_param_status VARCHAR(20),
    list_status     VARCHAR(20),
    operator        VARCHAR(50),
    remark          TEXT,
    create_by       VARCHAR(64) DEFAULT '',
    update_by       VARCHAR(64) DEFAULT '',
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE huawei_param IS 'HUAWEI参数表';
CREATE TRIGGER trg_huawei_param_update_time BEFORE UPDATE ON huawei_param
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- 签名文件信息表
-- ==========================
CREATE TABLE IF NOT EXISTS sign_file (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT REFERENCES company(id),
    store_file      VARCHAR(255),
    store_password  VARCHAR(100),
    key_alias       VARCHAR(100),
    remark          TEXT,
    create_by       VARCHAR(64) DEFAULT '',
    update_by       VARCHAR(64) DEFAULT '',
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE sign_file IS '签名文件信息表';
CREATE TRIGGER trg_sign_file_update_time BEFORE UPDATE ON sign_file
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- 权限组表
-- ==========================
CREATE TABLE IF NOT EXISTS permission_group (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name      VARCHAR(50) NOT NULL,
    group_permission TEXT,
    group_accounts  TEXT,
    remark          TEXT,
    create_by       VARCHAR(64) DEFAULT '',
    update_by       VARCHAR(64) DEFAULT '',
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE permission_group IS '权限组表';
CREATE TRIGGER trg_permission_group_update_time BEFORE UPDATE ON permission_group
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- 权限组模块范围表
-- ==========================
CREATE TABLE IF NOT EXISTS permission_scope (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id        BIGINT NOT NULL,
    scope           VARCHAR(16) NOT NULL,
    modules_text    TEXT,
    create_by       VARCHAR(64) DEFAULT '',
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by       VARCHAR(64) DEFAULT '',
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0,
    CONSTRAINT uk_permission_scope UNIQUE (group_id, scope)
);
COMMENT ON TABLE permission_scope IS '权限组模块范围表';
CREATE TRIGGER trg_permission_scope_update_time BEFORE UPDATE ON permission_scope
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- 用户表 (注意: 表名用 users, 避免 PG 保留字 user)
-- ==========================
CREATE TABLE IF NOT EXISTS users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(50) NOT NULL,
    password        VARCHAR(100) NOT NULL,
    real_name       VARCHAR(50),
    status          VARCHAR(20) DEFAULT 'active',
    remark          TEXT,
    create_by       VARCHAR(64) DEFAULT '',
    update_by       VARCHAR(64) DEFAULT '',
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE users IS '用户表';
CREATE UNIQUE INDEX IF NOT EXISTS uk_users_username ON users(username);
CREATE TRIGGER trg_users_update_time BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 用户权限组关联表
CREATE TABLE IF NOT EXISTS user_group (
    user_id BIGINT NOT NULL REFERENCES users(id),
    group_id BIGINT NOT NULL REFERENCES permission_group(id),
    PRIMARY KEY (user_id, group_id)
);
COMMENT ON TABLE user_group IS '用户权限组关联表';

-- ==========================
-- 操作日志表
-- ==========================
CREATE TABLE IF NOT EXISTS operation_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT,
    username        VARCHAR(50),
    module          VARCHAR(50),
    action          VARCHAR(20),
    target          VARCHAR(200),
    ip_address      VARCHAR(50),
    create_by       VARCHAR(64) DEFAULT '',
    update_by       VARCHAR(64) DEFAULT '',
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE operation_log IS '操作日志表';
CREATE TRIGGER trg_operation_log_update_time BEFORE UPDATE ON operation_log
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- 通知表
-- ==========================
CREATE TABLE IF NOT EXISTS notification (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR(100) NOT NULL,
    content         TEXT,
    module          VARCHAR(50),
    target_id       BIGINT,
    target_type     VARCHAR(20),
    sender_id       BIGINT,
    receiver_ids    TEXT,
    receiver_type   VARCHAR(20),
    is_pinned       SMALLINT DEFAULT 0,
    status          VARCHAR(20) DEFAULT 'unread',
    create_by       VARCHAR(64) DEFAULT '',
    update_by       VARCHAR(64) DEFAULT '',
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE notification IS '通知表';
CREATE TRIGGER trg_notification_update_time BEFORE UPDATE ON notification
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


-- ==========================
-- 默认数据由 DataInitializer 在应用启动时自动创建
-- ==========================

-- ==========================
-- 工具库表
-- ==========================
CREATE TABLE IF NOT EXISTS tool (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    VARCHAR(100) NOT NULL,
    description             VARCHAR(500),
    category                VARCHAR(50),
    version                 VARCHAR(50),
    status                  VARCHAR(20) DEFAULT '未运行',
    manager                 VARCHAR(50),
    run_mode                VARCHAR(20) DEFAULT 'Script',
    language                VARCHAR(20),
    interpreter_path        VARCHAR(500),
    script_path             VARCHAR(500),
    executable_path         VARCHAR(500),
    working_directory       VARCHAR(500),
    environment_variables   TEXT,
    default_argument_prefix VARCHAR(10) DEFAULT '--',
    git_url                 VARCHAR(500),
    clone_directory         VARCHAR(500),
    arguments_json          TEXT,
    notification_json       TEXT,
    is_system_builtin       SMALLINT DEFAULT 0,
    create_by               VARCHAR(64) DEFAULT '',
    create_time             TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by               VARCHAR(64) DEFAULT '',
    update_time             TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted              SMALLINT DEFAULT 0
);
COMMENT ON TABLE tool IS '工具库表';
CREATE TRIGGER trg_tool_update_time BEFORE UPDATE ON tool
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- RuoYi RBAC 系统表(由 F1 合并)
-- ==========================
CREATE TABLE IF NOT EXISTS sys_dept (
    dept_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id   BIGINT DEFAULT 0,
    ancestors   VARCHAR(500) DEFAULT '',
    dept_name   VARCHAR(30) NOT NULL,
    order_num   INT DEFAULT 0,
    leader      VARCHAR(20),
    phone       VARCHAR(11),
    email       VARCHAR(50),
    status      CHAR(1) DEFAULT '0',
    del_flag    CHAR(1) DEFAULT '0',
    create_by   VARCHAR(64) DEFAULT '',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by   VARCHAR(64) DEFAULT '',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    remark      VARCHAR(500)
);
COMMENT ON TABLE sys_dept IS '部门表';

-- 岗位表
CREATE TABLE IF NOT EXISTS sys_post (
    post_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_code   VARCHAR(64) NOT NULL,
    post_name   VARCHAR(50) NOT NULL,
    post_sort   INT DEFAULT 0,
    status      CHAR(1) DEFAULT '0',
    create_by   VARCHAR(64) DEFAULT '',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by   VARCHAR(64) DEFAULT '',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    remark      VARCHAR(500)
);
COMMENT ON TABLE sys_post IS '岗位信息表';

-- 用户表
CREATE TABLE IF NOT EXISTS sys_user (
    user_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_id     BIGINT,
    user_name   VARCHAR(30) NOT NULL,
    nick_name   VARCHAR(30) NOT NULL,
    email       VARCHAR(50) DEFAULT '',
    phonenumber VARCHAR(11) DEFAULT '',
    sex         CHAR(1) DEFAULT '0',
    avatar      VARCHAR(255) DEFAULT '',
    password    VARCHAR(100) DEFAULT '',
    status      CHAR(1) DEFAULT '0',
    login_ip    VARCHAR(128) DEFAULT '',
    login_date  TIMESTAMP,
    is_deleted  SMALLINT DEFAULT 0,
    create_by   VARCHAR(64) DEFAULT '',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by   VARCHAR(64) DEFAULT '',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    remark      VARCHAR(500)
);
COMMENT ON TABLE sys_user IS '用户信息表';
CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_user_user_name ON sys_user(user_name);

-- 角色表
CREATE TABLE IF NOT EXISTS sys_role (
    role_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name   VARCHAR(30) NOT NULL,
    role_key    VARCHAR(100) NOT NULL,
    role_sort   INT DEFAULT 0,
    data_scope  CHAR(1) DEFAULT '1',
    menu_check_strictly SMALLINT DEFAULT 1,
    dept_check_strictly SMALLINT DEFAULT 1,
    status      CHAR(1) DEFAULT '0',
    del_flag    CHAR(1) DEFAULT '0',
    create_by   VARCHAR(64) DEFAULT '',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by   VARCHAR(64) DEFAULT '',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    remark      VARCHAR(500)
);
COMMENT ON TABLE sys_role IS '角色信息表';

-- 菜单/权限表
CREATE TABLE IF NOT EXISTS sys_menu (
    menu_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_name   VARCHAR(50) NOT NULL,
    parent_id   BIGINT DEFAULT 0,
    order_num   INT DEFAULT 0,
    path        VARCHAR(200) DEFAULT '',
    component   VARCHAR(255),
    query       VARCHAR(255),
    is_frame    CHAR(1) DEFAULT '1',
    is_cache    CHAR(1) DEFAULT '0',
    menu_type   CHAR(1) DEFAULT '',
    visible     CHAR(1) DEFAULT '0',
    status      CHAR(1) DEFAULT '0',
    perms       VARCHAR(100),
    icon        VARCHAR(100) DEFAULT '#',
    create_by   VARCHAR(64) DEFAULT '',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by   VARCHAR(64) DEFAULT '',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    remark      VARCHAR(500)
);
COMMENT ON TABLE sys_menu IS '菜单权限表';

-- 用户-角色关联表
CREATE TABLE IF NOT EXISTS sys_user_role (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id)
);
COMMENT ON TABLE sys_user_role IS '用户和角色关联表';

-- 角色-菜单关联表
CREATE TABLE IF NOT EXISTS sys_role_menu (
    role_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, menu_id)
);
COMMENT ON TABLE sys_role_menu IS '角色和菜单关联表';

-- 参数配置表 (Agent 2 用)
CREATE TABLE IF NOT EXISTS sys_config (
    config_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_name  VARCHAR(100) DEFAULT '',
    config_key   VARCHAR(100) DEFAULT '',
    config_value VARCHAR(500) DEFAULT '',
    config_type  CHAR(1) DEFAULT 'N',
    is_builtin   CHAR(1) DEFAULT 'N',
    create_by    VARCHAR(64) DEFAULT '',
    create_time  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by    VARCHAR(64) DEFAULT '',
    update_time  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    remark       VARCHAR(500)
);
COMMENT ON TABLE sys_config IS '参数配置表';

-- 通知公告表 (Agent 2 用)
CREATE TABLE IF NOT EXISTS sys_notice (
    notice_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notice_title   VARCHAR(50) NOT NULL,
    notice_type    CHAR(1) NOT NULL,
    notice_content TEXT,
    status         CHAR(1) DEFAULT '0',
    create_by      VARCHAR(64) DEFAULT '',
    create_time    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by      VARCHAR(64) DEFAULT '',
    update_time    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    remark         VARCHAR(255)
);
COMMENT ON TABLE sys_notice IS '通知公告表';

-- 操作日志表 (Agent 2 用)
CREATE TABLE IF NOT EXISTS sys_oper_log (
    oper_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          VARCHAR(50) DEFAULT '',
    business_type  INT DEFAULT 0,
    method         VARCHAR(100) DEFAULT '',
    request_method VARCHAR(10) DEFAULT '',
    operator_type  INT DEFAULT 0,
    oper_name      VARCHAR(50) DEFAULT '',
    dept_name      VARCHAR(50) DEFAULT '',
    oper_url       VARCHAR(255) DEFAULT '',
    oper_ip        VARCHAR(128) DEFAULT '',
    oper_param     VARCHAR(2000) DEFAULT '',
    json_result    VARCHAR(2000) DEFAULT '',
    status         INT DEFAULT 0,
    error_msg      VARCHAR(2000) DEFAULT '',
    oper_time      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE sys_oper_log IS '操作日志记录';

-- 登录日志表 (Agent 2 用)
CREATE TABLE IF NOT EXISTS sys_logininfor (
    info_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name      VARCHAR(50) DEFAULT '',
    ipaddr         VARCHAR(128) DEFAULT '',
    login_location VARCHAR(255) DEFAULT '',
    browser        VARCHAR(50) DEFAULT '',
    os             VARCHAR(50) DEFAULT '',
    status         CHAR(1) DEFAULT '0',
    msg            VARCHAR(255) DEFAULT '',
    login_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE sys_logininfor IS '系统访问记录';

-- ==========================
