-- ============================================================
-- Zlinks Package System — PostgreSQL 15+ 初始化脚本
-- ============================================================
-- 使用前请先创建数据库:
--   createdb zlinks_package_system
-- 然后执行:
--   psql -d zlinks_package_system -f init-database-pgsql.sql
-- ============================================================

-- 通用触发器函数: 自动更新 update_time
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.update_time = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ==========================
-- 游戏表
-- ==========================
CREATE TABLE IF NOT EXISTS game (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_name       VARCHAR(100) NOT NULL,
    game_direction  VARCHAR(20) NOT NULL,
    source          VARCHAR(50),
    git_url         VARCHAR(255),
    priority        INT DEFAULT 0,
    tags            VARCHAR(255),
    project_type    VARCHAR(50),
    manager         VARCHAR(50),
    white_branch    VARCHAR(100),
    status          VARCHAR(20) DEFAULT 'active',
    retention_record TEXT,
    android_folder_name VARCHAR(100),
    remark          TEXT,
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE game IS '游戏表';
CREATE TRIGGER trg_game_update_time BEFORE UPDATE ON game
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- 平台表
-- ==========================
CREATE TABLE IF NOT EXISTS platform (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_name   VARCHAR(100) NOT NULL,
    platform_code   VARCHAR(50),
    sort_order      INT DEFAULT 0,
    status          VARCHAR(20) DEFAULT 'active',
    remark          TEXT,
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE platform IS '平台表';
CREATE TRIGGER trg_platform_update_time BEFORE UPDATE ON platform
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- 软著表
-- ==========================
CREATE TABLE IF NOT EXISTS copyright (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    copyright_name  VARCHAR(100) NOT NULL,
    copyright_owner VARCHAR(100),
    copyright_number VARCHAR(50),
    remark          TEXT,
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE copyright IS '软著表';
CREATE TRIGGER trg_copyright_update_time BEFORE UPDATE ON copyright
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- 主体公司表
-- ==========================
CREATE TABLE IF NOT EXISTS company (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name    VARCHAR(100) NOT NULL,
    platform_id     BIGINT,
    account         VARCHAR(100),
    password        VARCHAR(100),
    remark          TEXT,
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE company IS '主体公司表';
CREATE TRIGGER trg_company_update_time BEFORE UPDATE ON company
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- 平台匹配表
-- ==========================
CREATE TABLE IF NOT EXISTS platform_match (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT REFERENCES company(id),
    original_game   VARCHAR(100),
    current_game_name VARCHAR(100),
    batch           VARCHAR(50),
    package_mode    VARCHAR(20),
    sdk_version     VARCHAR(50),
    apk_version     VARCHAR(20),
    platform_status VARCHAR(20) DEFAULT 'pending',
    remark          TEXT,
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE platform_match IS '平台匹配表';
CREATE TRIGGER trg_platform_match_update_time BEFORE UPDATE ON platform_match
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- 产品表
-- ==========================
CREATE TABLE IF NOT EXISTS product (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    copyright_id    BIGINT REFERENCES copyright(id),
    game_id         BIGINT REFERENCES game(id),
    company_id      BIGINT REFERENCES company(id),
    platform_id     BIGINT,
    package_name    VARCHAR(100),
    sdk_version     VARCHAR(50),
    apk_version     VARCHAR(50),
    batch           VARCHAR(50),
    package_mode    VARCHAR(20),
    status          VARCHAR(20) DEFAULT 'pending',
    remark          TEXT,
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE product IS '产品表';
CREATE TRIGGER trg_product_update_time BEFORE UPDATE ON product
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- 荣耀参数表
-- ==========================
CREATE TABLE IF NOT EXISTS honor_param (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      BIGINT NOT NULL REFERENCES product(id),
    package_name    VARCHAR(100),
    app_id          VARCHAR(100),
    app_secret      VARCHAR(100),
    media_id        VARCHAR(100),
    agconnect_path  VARCHAR(255),
    td_app_id       VARCHAR(100),
    ad_param_status VARCHAR(20),
    list_status     VARCHAR(20),
    operator        VARCHAR(50),
    remark          TEXT,
    create_by       VARCHAR(64) DEFAULT '',
    update_by       VARCHAR(64) DEFAULT '',
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE honor_param IS '荣耀参数表';
CREATE TRIGGER trg_honor_param_update_time BEFORE UPDATE ON honor_param
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- VIVO参数表
-- ==========================
CREATE TABLE IF NOT EXISTS vivo_param (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      BIGINT NOT NULL REFERENCES product(id),
    app_id          VARCHAR(100),
    contract_status VARCHAR(20),
    media_id        VARCHAR(100),
    td_app_id       VARCHAR(100),
    ad_param_status VARCHAR(20),
    list_status     VARCHAR(20),
    operator        VARCHAR(50),
    remark          TEXT,
    create_by       VARCHAR(64) DEFAULT '',
    update_by       VARCHAR(64) DEFAULT '',
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE vivo_param IS 'VIVO参数表';
CREATE TRIGGER trg_vivo_param_update_time BEFORE UPDATE ON vivo_param
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- HUAWEI参数表
-- ==========================
CREATE TABLE IF NOT EXISTS huawei_param (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      BIGINT NOT NULL REFERENCES product(id),
    package_name    VARCHAR(100),
    app_id          VARCHAR(100),
    agconnect_path  VARCHAR(255),
    td_app_id       VARCHAR(100),
    ad_param_status VARCHAR(20),
    list_status     VARCHAR(20),
    operator        VARCHAR(50),
    remark          TEXT,
    create_by       VARCHAR(64) DEFAULT '',
    update_by       VARCHAR(64) DEFAULT '',
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE huawei_param IS 'HUAWEI参数表';
CREATE TRIGGER trg_huawei_param_update_time BEFORE UPDATE ON huawei_param
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- 签名文件信息表
-- ==========================
CREATE TABLE IF NOT EXISTS sign_file (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT REFERENCES company(id),
    store_file      VARCHAR(255),
    store_password  VARCHAR(100),
    key_alias       VARCHAR(100),
    remark          TEXT,
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE sign_file IS '签名文件信息表';
CREATE TRIGGER trg_sign_file_update_time BEFORE UPDATE ON sign_file
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- 权限组表
-- ==========================
CREATE TABLE IF NOT EXISTS permission_group (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name      VARCHAR(50) NOT NULL,
    group_permission TEXT,
    group_accounts  TEXT,
    remark          TEXT,
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE permission_group IS '权限组表';
CREATE TRIGGER trg_permission_group_update_time BEFORE UPDATE ON permission_group
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- 权限组模块范围表
-- ==========================
CREATE TABLE IF NOT EXISTS permission_scope (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id        BIGINT NOT NULL,
    scope           VARCHAR(16) NOT NULL,
    modules_text    TEXT,
    create_by       VARCHAR(64) DEFAULT '',
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by       VARCHAR(64) DEFAULT '',
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0,
    CONSTRAINT uk_permission_scope UNIQUE (group_id, scope)
);
COMMENT ON TABLE permission_scope IS '权限组模块范围表';
CREATE TRIGGER trg_permission_scope_update_time BEFORE UPDATE ON permission_scope
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- 用户表 (注意: 表名用 users, 避免 PG 保留字 user)
-- ==========================
CREATE TABLE IF NOT EXISTS users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(50) NOT NULL,
    password        VARCHAR(100) NOT NULL,
    real_name       VARCHAR(50),
    status          VARCHAR(20) DEFAULT 'active',
    remark          TEXT,
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE users IS '用户表';
CREATE UNIQUE INDEX IF NOT EXISTS uk_users_username ON users(username);
CREATE TRIGGER trg_users_update_time BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 用户权限组关联表
CREATE TABLE IF NOT EXISTS user_group (
    user_id BIGINT NOT NULL REFERENCES users(id),
    group_id BIGINT NOT NULL REFERENCES permission_group(id),
    PRIMARY KEY (user_id, group_id)
);
COMMENT ON TABLE user_group IS '用户权限组关联表';

-- ==========================
-- 操作日志表
-- ==========================
CREATE TABLE IF NOT EXISTS operation_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT,
    username        VARCHAR(50),
    module          VARCHAR(50),
    action          VARCHAR(20),
    target          VARCHAR(200),
    ip_address      VARCHAR(50),
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE operation_log IS '操作日志表';
CREATE TRIGGER trg_operation_log_update_time BEFORE UPDATE ON operation_log
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- 通知表
-- ==========================
CREATE TABLE IF NOT EXISTS notification (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR(100) NOT NULL,
    content         TEXT,
    module          VARCHAR(50),
    target_id       BIGINT,
    target_type     VARCHAR(20),
    sender_id       BIGINT,
    receiver_ids    TEXT,
    receiver_type   VARCHAR(20),
    is_pinned       SMALLINT DEFAULT 0,
    status          VARCHAR(20) DEFAULT 'unread',
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE notification IS '通知表';
CREATE TRIGGER trg_notification_update_time BEFORE UPDATE ON notification
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


-- ==========================
-- 默认数据由 DataInitializer 在应用启动时自动创建
-- ==========================
