-- ============================================================
-- Zlinks Package System — PostgreSQL 15+ 初始化脚本
-- ============================================================
-- 使用前请先创建数据库:
--   createdb zlinks_package_system
-- 然后执行:
--   psql -d zlinks_package_system -f init-database-pgsql.sql
-- ============================================================

-- 通用触发器函数: 自动更新 update_time
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.update_time = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ==========================
-- 游戏表
-- ==========================
CREATE TABLE IF NOT EXISTS game (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_name       VARCHAR(100) NOT NULL,
    game_direction  VARCHAR(20) NOT NULL,
    source          VARCHAR(50),
    git_url         VARCHAR(255),
    priority        INT DEFAULT 0,
    tags            VARCHAR(255),
    project_type    VARCHAR(50),
    manager         VARCHAR(50),
    white_branch    VARCHAR(100),
    status          VARCHAR(20) DEFAULT 'active',
    retention_record TEXT,
    android_folder_name VARCHAR(100),
    remark          TEXT,
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE game IS '游戏表';
CREATE TRIGGER trg_game_update_time BEFORE UPDATE ON game
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- 软著表
-- ==========================
CREATE TABLE IF NOT EXISTS copyright (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    copyright_name  VARCHAR(100) NOT NULL,
    copyright_owner VARCHAR(100),
    copyright_number VARCHAR(50),
    remark          TEXT,
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE copyright IS '软著表';
CREATE TRIGGER trg_copyright_update_time BEFORE UPDATE ON copyright
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- 主体公司表
-- ==========================
CREATE TABLE IF NOT EXISTS company (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name    VARCHAR(100) NOT NULL,
    platform        VARCHAR(50),
    account         VARCHAR(100),
    password        VARCHAR(100),
    remark          TEXT,
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE company IS '主体公司表';
CREATE TRIGGER trg_company_update_time BEFORE UPDATE ON company
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- 平台匹配表
-- ==========================
CREATE TABLE IF NOT EXISTS platform_match (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT REFERENCES company(id),
    original_game   VARCHAR(100),
    current_game_name VARCHAR(100),
    batch           VARCHAR(50),
    package_mode    VARCHAR(20),
    sdk_version     VARCHAR(50),
    apk_version     VARCHAR(20),
    platform_status VARCHAR(20) DEFAULT 'pending',
    remark          TEXT,
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE platform_match IS '平台匹配表';
CREATE TRIGGER trg_platform_match_update_time BEFORE UPDATE ON platform_match
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- 荣耀参数表
-- ==========================
CREATE TABLE IF NOT EXISTS honor_param (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id         BIGINT REFERENCES game(id),
    package_name    VARCHAR(100),
    app_id          VARCHAR(100),
    app_secret      VARCHAR(100),
    media_id        VARCHAR(100),
    agconnect_path  VARCHAR(255),
    td_app_id       VARCHAR(100),
    ad_param_status VARCHAR(20),
    list_status     VARCHAR(20),
    operator        VARCHAR(50),
    remark          TEXT,
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE honor_param IS '荣耀参数表';
CREATE TRIGGER trg_honor_param_update_time BEFORE UPDATE ON honor_param
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- VIVO参数表
-- ==========================
CREATE TABLE IF NOT EXISTS vivo_param (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id         BIGINT REFERENCES game(id),
    app_id          VARCHAR(100),
    contract_status VARCHAR(20),
    media_id        VARCHAR(100),
    td_app_id       VARCHAR(100),
    ad_param_status VARCHAR(20),
    list_status     VARCHAR(20),
    operator        VARCHAR(50),
    remark          TEXT,
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE vivo_param IS 'VIVO参数表';
CREATE TRIGGER trg_vivo_param_update_time BEFORE UPDATE ON vivo_param
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- HUAWEI参数表
-- ==========================
CREATE TABLE IF NOT EXISTS huawei_param (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id         BIGINT REFERENCES game(id),
    package_name    VARCHAR(100),
    app_id          VARCHAR(100),
    agconnect_path  VARCHAR(255),
    td_app_id       VARCHAR(100),
    ad_param_status VARCHAR(20),
    list_status     VARCHAR(20),
    operator        VARCHAR(50),
    remark          TEXT,
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE huawei_param IS 'HUAWEI参数表';
CREATE TRIGGER trg_huawei_param_update_time BEFORE UPDATE ON huawei_param
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- 签名文件信息表
-- ==========================
CREATE TABLE IF NOT EXISTS sign_file (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT REFERENCES company(id),
    store_file      VARCHAR(255),
    store_password  VARCHAR(100),
    key_alias       VARCHAR(100),
    remark          TEXT,
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE sign_file IS '签名文件信息表';
CREATE TRIGGER trg_sign_file_update_time BEFORE UPDATE ON sign_file
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- 权限组表
-- ==========================
CREATE TABLE IF NOT EXISTS permission_group (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name      VARCHAR(50) NOT NULL,
    group_permission TEXT,
    group_accounts  TEXT,
    remark          TEXT,
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE permission_group IS '权限组表';
CREATE TRIGGER trg_permission_group_update_time BEFORE UPDATE ON permission_group
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- 用户表 (注意: 表名用 users, 避免 PG 保留字 user)
-- ==========================
CREATE TABLE IF NOT EXISTS users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(50) NOT NULL,
    password        VARCHAR(100) NOT NULL,
    real_name       VARCHAR(50),
    status          VARCHAR(20) DEFAULT 'active',
    group_id        BIGINT REFERENCES permission_group(id),
    remark          TEXT,
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE users IS '用户表';
CREATE UNIQUE INDEX IF NOT EXISTS uk_users_username ON users(username);
CREATE TRIGGER trg_users_update_time BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================
-- 通知表
-- ==========================
CREATE TABLE IF NOT EXISTS notification (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR(100) NOT NULL,
    content         TEXT,
    module          VARCHAR(50),
    target_id       BIGINT,
    target_type     VARCHAR(20),
    sender_id       BIGINT,
    receiver_ids    TEXT,
    receiver_type   VARCHAR(20),
    is_pinned       SMALLINT DEFAULT 0,
    status          VARCHAR(20) DEFAULT 'unread',
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted      SMALLINT DEFAULT 0
);
COMMENT ON TABLE notification IS '通知表';
CREATE TRIGGER trg_notification_update_time BEFORE UPDATE ON notification
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


-- ==========================
-- 插入默认权限组
-- ==========================
INSERT INTO permission_group (group_name, group_permission, remark) VALUES
('管理员组', '{"modules":["all"]}', '系统管理员，拥有所有权限'),
('开发组', '{"modules":["games","products"]}', '开发人员，负责游戏和产品管理'),
('测试组', '{"modules":["tests"]}', '测试人员，负责测试管理'),
('运营组', '{"modules":["products","companies"]}', '运营人员，负责产品和公司管理');

-- ==========================
-- 插入默认管理员用户 (密码: admin123)
-- BCrypt 哈希值对应密码 admin123
-- ==========================
INSERT INTO users (username, password, real_name, status, group_id) VALUES
('admin', '$2a$10$EqKcp1WFKVQIShMPC7B3kuznX9gAZMsVnSNjN0ABNuHVBCpzqABae', '系统管理员', 'active', 1);
