-- ============================================================
-- Zlinks Package System → RuoYi RBAC PostgreSQL 迁移脚本
-- ============================================================
-- 用法: psql -d zlinks_package_system -f migrate-to-ruoyi-pgsql.sql
-- 注意:
--   1. 必须在同一事务中执行; 失败自动回滚 (此脚本使用 \set ON_ERROR_STOP on)
--   2. 旧表会重命名为 *_legacy 保留, 不删除数据
--   3. 数据迁移仅在目标表为空时执行, 重复执行安全
--   4. 回退脚本见 migrate-rollback-pgsql.sql
-- ============================================================

\set ON_ERROR_STOP on
BEGIN;

-- ==========================
-- 1. 新建 sys_* 表
-- ==========================

-- 部门表
CREATE TABLE IF NOT EXISTS sys_dept (
    dept_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id   BIGINT DEFAULT 0,
    ancestors   VARCHAR(500) DEFAULT '',
    dept_name   VARCHAR(30) NOT NULL,
    order_num   INT DEFAULT 0,
    leader      VARCHAR(20),
    phone       VARCHAR(11),
    email       VARCHAR(50),
    status      CHAR(1) DEFAULT '0',
    del_flag    CHAR(1) DEFAULT '0',
    create_by   VARCHAR(64) DEFAULT '',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by   VARCHAR(64) DEFAULT '',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    remark      VARCHAR(500)
);
COMMENT ON TABLE sys_dept IS '部门表';

-- 岗位表
CREATE TABLE IF NOT EXISTS sys_post (
    post_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_code   VARCHAR(64) NOT NULL,
    post_name   VARCHAR(50) NOT NULL,
    post_sort   INT DEFAULT 0,
    status      CHAR(1) DEFAULT '0',
    create_by   VARCHAR(64) DEFAULT '',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by   VARCHAR(64) DEFAULT '',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    remark      VARCHAR(500)
);
COMMENT ON TABLE sys_post IS '岗位信息表';

-- 用户表
CREATE TABLE IF NOT EXISTS sys_user (
    user_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_id     BIGINT,
    user_name   VARCHAR(30) NOT NULL,
    nick_name   VARCHAR(30) NOT NULL,
    email       VARCHAR(50) DEFAULT '',
    phonenumber VARCHAR(11) DEFAULT '',
    sex         CHAR(1) DEFAULT '0',
    avatar      VARCHAR(255) DEFAULT '',
    password    VARCHAR(100) DEFAULT '',
    status      CHAR(1) DEFAULT '0',
    login_ip    VARCHAR(128) DEFAULT '',
    login_date  TIMESTAMP,
    is_deleted  SMALLINT DEFAULT 0,
    create_by   VARCHAR(64) DEFAULT '',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by   VARCHAR(64) DEFAULT '',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    remark      VARCHAR(500)
);
COMMENT ON TABLE sys_user IS '用户信息表';
CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_user_user_name ON sys_user(user_name);

-- 角色表
CREATE TABLE IF NOT EXISTS sys_role (
    role_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name   VARCHAR(30) NOT NULL,
    role_key    VARCHAR(100) NOT NULL,
    role_sort   INT DEFAULT 0,
    data_scope  CHAR(1) DEFAULT '1',
    menu_check_strictly SMALLINT DEFAULT 1,
    dept_check_strictly SMALLINT DEFAULT 1,
    status      CHAR(1) DEFAULT '0',
    del_flag    CHAR(1) DEFAULT '0',
    create_by   VARCHAR(64) DEFAULT '',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by   VARCHAR(64) DEFAULT '',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    remark      VARCHAR(500)
);
COMMENT ON TABLE sys_role IS '角色信息表';

-- 菜单/权限表
CREATE TABLE IF NOT EXISTS sys_menu (
    menu_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_name   VARCHAR(50) NOT NULL,
    parent_id   BIGINT DEFAULT 0,
    order_num   INT DEFAULT 0,
    path        VARCHAR(200) DEFAULT '',
    component   VARCHAR(255),
    query       VARCHAR(255),
    is_frame    CHAR(1) DEFAULT '1',
    is_cache    CHAR(1) DEFAULT '0',
    menu_type   CHAR(1) DEFAULT '',
    visible     CHAR(1) DEFAULT '0',
    status      CHAR(1) DEFAULT '0',
    perms       VARCHAR(100),
    icon        VARCHAR(100) DEFAULT '#',
    create_by   VARCHAR(64) DEFAULT '',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by   VARCHAR(64) DEFAULT '',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    remark      VARCHAR(500)
);
COMMENT ON TABLE sys_menu IS '菜单权限表';

-- 用户-角色关联表
CREATE TABLE IF NOT EXISTS sys_user_role (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id)
);
COMMENT ON TABLE sys_user_role IS '用户和角色关联表';

-- 角色-菜单关联表
CREATE TABLE IF NOT EXISTS sys_role_menu (
    role_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, menu_id)
);
COMMENT ON TABLE sys_role_menu IS '角色和菜单关联表';

-- 参数配置表 (Agent 2 用)
CREATE TABLE IF NOT EXISTS sys_config (
    config_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_name  VARCHAR(100) DEFAULT '',
    config_key   VARCHAR(100) DEFAULT '',
    config_value VARCHAR(500) DEFAULT '',
    config_type  CHAR(1) DEFAULT 'N',
    is_builtin   CHAR(1) DEFAULT 'N',
    create_by    VARCHAR(64) DEFAULT '',
    create_time  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by    VARCHAR(64) DEFAULT '',
    update_time  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    remark       VARCHAR(500)
);
COMMENT ON TABLE sys_config IS '参数配置表';

-- 通知公告表 (Agent 2 用)
CREATE TABLE IF NOT EXISTS sys_notice (
    notice_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notice_title   VARCHAR(50) NOT NULL,
    notice_type    CHAR(1) NOT NULL,
    notice_content TEXT,
    status         CHAR(1) DEFAULT '0',
    create_by      VARCHAR(64) DEFAULT '',
    create_time    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by      VARCHAR(64) DEFAULT '',
    update_time    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    remark         VARCHAR(255)
);
COMMENT ON TABLE sys_notice IS '通知公告表';

-- 操作日志表 (Agent 2 用)
CREATE TABLE IF NOT EXISTS sys_oper_log (
    oper_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          VARCHAR(50) DEFAULT '',
    business_type  INT DEFAULT 0,
    method         VARCHAR(100) DEFAULT '',
    request_method VARCHAR(10) DEFAULT '',
    operator_type  INT DEFAULT 0,
    oper_name      VARCHAR(50) DEFAULT '',
    dept_name      VARCHAR(50) DEFAULT '',
    oper_url       VARCHAR(255) DEFAULT '',
    oper_ip        VARCHAR(128) DEFAULT '',
    oper_param     VARCHAR(2000) DEFAULT '',
    json_result    VARCHAR(2000) DEFAULT '',
    status         INT DEFAULT 0,
    error_msg      VARCHAR(2000) DEFAULT '',
    oper_time      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE sys_oper_log IS '操作日志记录';

-- 登录日志表 (Agent 2 用)
CREATE TABLE IF NOT EXISTS sys_logininfor (
    info_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name      VARCHAR(50) DEFAULT '',
    ipaddr         VARCHAR(128) DEFAULT '',
    login_location VARCHAR(255) DEFAULT '',
    browser        VARCHAR(50) DEFAULT '',
    os             VARCHAR(50) DEFAULT '',
    status         CHAR(1) DEFAULT '0',
    msg            VARCHAR(255) DEFAULT '',
    login_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE sys_logininfor IS '系统访问记录';

-- ==========================
-- 2. 数据迁移: users → sys_user
-- ==========================
INSERT INTO sys_user (user_name, nick_name, password, status, is_deleted, create_by, create_time, update_time, remark)
SELECT
    username,
    COALESCE(real_name, username),
    password,
    CASE WHEN status = 'active' THEN '0' ELSE '1' END,
    COALESCE(is_deleted, 0),
    'migration',
    COALESCE(create_time, CURRENT_TIMESTAMP),
    COALESCE(update_time, CURRENT_TIMESTAMP),
    COALESCE(remark, '')
FROM users
WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE sys_user.user_name = users.username);

-- ==========================
-- 3. 数据迁移: permission_group → sys_role
--    permission_group.permissions 是 JSON, 这里仅保留原文本到 remark,
--    角色 role_key 用 "group_{id}" 形式
-- ==========================
INSERT INTO sys_role (role_name, role_key, role_sort, data_scope, status, del_flag, create_by, create_time, update_time, remark)
SELECT
    group_name,
    'group_' || id::text,
    id,
    '1',
    '0',
    '0',
    'migration',
    COALESCE(create_time, CURRENT_TIMESTAMP),
    COALESCE(update_time, CURRENT_TIMESTAMP),
    COALESCE(group_permission, '')
FROM permission_group
WHERE NOT EXISTS (SELECT 1 FROM sys_role WHERE sys_role.role_key = 'group_' || permission_group.id::text);

-- ==========================
-- 4. 数据迁移: user_group → sys_user_role
-- ==========================
INSERT INTO sys_user_role (user_id, role_id)
SELECT ug.user_id, ug.group_id
FROM user_group ug
WHERE EXISTS (SELECT 1 FROM sys_user WHERE sys_user.user_id = ug.user_id)
  AND EXISTS (SELECT 1 FROM sys_role WHERE sys_role.role_id = ug.group_id)
  AND NOT EXISTS (
    SELECT 1 FROM sys_user_role sur
    WHERE sur.user_id = ug.user_id AND sur.role_id = ug.group_id
  );

-- ==========================
-- 5. 旧表归档: 重命名为 *_legacy
-- ==========================
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'users' AND table_schema = current_schema())
       AND NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'users_legacy' AND table_schema = current_schema()) THEN
        EXECUTE 'ALTER TABLE users RENAME TO users_legacy';
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'permission_group' AND table_schema = current_schema())
       AND NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'permission_group_legacy' AND table_schema = current_schema()) THEN
        EXECUTE 'ALTER TABLE permission_group RENAME TO permission_group_legacy';
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'user_group' AND table_schema = current_schema())
       AND NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'user_group_legacy' AND table_schema = current_schema()) THEN
        EXECUTE 'ALTER TABLE user_group RENAME TO user_group_legacy';
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'notification' AND table_schema = current_schema())
       AND NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'notification_legacy' AND table_schema = current_schema()) THEN
        EXECUTE 'ALTER TABLE notification RENAME TO notification_legacy';
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'operation_log' AND table_schema = current_schema())
       AND NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'operation_log_legacy' AND table_schema = current_schema()) THEN
        EXECUTE 'ALTER TABLE operation_log RENAME TO operation_log_legacy';
    END IF;
END $$;

COMMIT;

-- ============================================================
-- 默认菜单树 / 默认角色 / 默认用户 由后端 DataInitializer 启动时插入
-- 详见: com.zlinks.package_system.config.DataInitializer
-- ============================================================